
export EDITOR=nvim

[ -e $HOME/.profile ] && source $HOME/.profile
[ -e $HOME/.bashrc ] && source $HOME/.bashrc
[ -e $HOME/.bash_aliases ] && source $HOME/.bash_aliases
[ -e $HOME/.bash_aliases_local ] && source $HOME/.bash_aliases_local

[ -e $HOME/.env_local ] && source $HOME/.env_local
[ -e $HOME/.env_unmanaged ] && source $HOME/.env_unmanaged

# OS X specific stuff
if [ $(uname) == 'Darwin' ]; then
  if [ -e "/opt/homebrew/bin" ]; then
    export PATH="/opt/homebrew/bin:$PATH"
    eval "$(brew shellenv)"
  fi

  if command -v brew > /dev/null && [ -f $(brew --prefix)/etc/bash_completion ]; then
    source $(brew --prefix)/etc/bash_completion
  fi
  if command -v brew > /dev/null && [ -f $(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc ]; then
    source $(brew --prefix)/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc
  fi

fi

if [ $(uname) == 'Linux' ]; then
  if [ -e "/home/linuxbrew" ]; then
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  fi
fi

if command -v rbenv > /dev/null; then
  eval "$(rbenv init -)"
fi

if command -v pyenv > /dev/null ; then
  eval "$(pyenv init -)"
  eval "$(pyenv init --path)"
  eval "$(pyenv virtualenv-init -)"
fi

if [ -e "$HOME/.nvm" ]; then
  source /usr/local/opt/nvm/nvm.sh
  export NVM_DIR="$HOME/.nvm"
fi

[ -e $HOME/.bash_profile_local ] && source $HOME/.bash_profile_local
