export EDITOR=vim

[ -e $HOME/.profile ] && source $HOME/.profile
[ -e $HOME/.bashrc ] && source $HOME/.bashrc
[ -e $HOME/.bash_aliases ] && source $HOME/.bash_aliases
[ -e $HOME/.bash_aliases_local ] && source $HOME/.bash_aliases_local

[ -e $HOME/.env_local ] && source $HOME/.env_local
[ -e $HOME/.env_unmanaged ] && source $HOME/.env_unmanaged

# OS X specific stuff
if [ $(uname) == 'Darwin' ]; then
  if command -v brew > /dev/null && [ -f $(brew --prefix)/etc/bash_completion ]; then
    source $(brew --prefix)/etc/bash_completion
  fi

  if [ -e "$HOME/.nvm" ]; then
    export NVM_DIR="$HOME/.nvm"
    source /usr/local/opt/nvm/nvm.sh
  else
    echo "$HOME/.nvm doesn't exist, not sourcing NVM" >&2
  fi
fi
