export EDITOR=vim

[ -e $HOME/.profile ] && source $HOME/.profile
[ -e $HOME/.bashrc ] && source $HOME/.bashrc
[ -e $HOME/.bash_aliases ] && source $HOME/.bash_aliases
[ -e $HOME/.bash_aliases_local ] && source $HOME/.bash_aliases_local

[ -e $HOME/.env_local ] && source $HOME/.env_local
[ -e $HOME/.env_unmanaged ] && source $HOME/.env_unmanaged

if command -v brew > /dev/null && [ -f $(brew --prefix)/etc/bash_completion ]; then
  source $(brew --prefix)/etc/bash_completion
fi
